### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yiboliu31** [Ghustwb/MobileNet-SSD-TensorRT#1]
I met an error in TX2（TesnorRT 4）,Assertion 'blobNameToTensor != nullptr' failed.
Have you tried with TensorRT 4?

**Comment by Ghustwb** [comment]
Yes，tensorRT4 could run successfully。
You should modify some code in pluginImplement.cpp
uncomment line 525，comment line 524
uncomment line 533,534,535

**Comment by yiboliu31** [comment]
Thanks for your great help!!!! It worked!!!
i will work on my own prototxt and model ,Thank you again
