### ISSUE TITLE
how to get layer output

### ISSUE THREAD

**Issue by ghost** [Ghustwb/MobileNet-SSD-TensorRT#11]
thanks for your work and how to get layer output for debug with tensorrt?

**Comment by Ghustwb** [comment]
Like this, mbox_conf_softmax,you can print it
const char* OUTPUT1 = "mbox_conf_softmax";
DimsCHW dims1    = tensorNet.getTensorDims(OUTPUT1);
float* output1 = allocateMemory( dims1    , (char*)"output1");

**Comment by ghost** [comment]
thx，I had solve this problem like you
