### ISSUE TITLE
one question i want to ask why is nms not used in this project. thank you in advance

### ISSUE THREAD

**Issue by zhouleidcc** [Ghustwb/MobileNet-SSD-TensorRT#12]

**Comment by Ghustwb** [comment]
NMS was used in detection_out layer,I used TensorRT's API , so you could not see it.

**Comment by zhouleidcc** [comment]
Thank you for your reply. But I am still confuse. What I concern is whether I need to apply NMS after getting boxes through API tensorNet.imageInference. Look forward to your reply, thanks again.
