### ISSUE TITLE
Which are classes in your model?

### ISSUE THREAD

**Issue by PiyalGeorge** [Ghustwb/MobileNet-SSD-TensorRT#16]
Hi @Ghustwb , I tested with your existing model in this repo, and its very accurate and almost perfect. Can you please tell me which are the classes in your existing model. i saw car and person and one must be background, but can you tell me which are the other classes?

I also would like to train a model as better and perfect as yours, can you tell me which dataset you used?, did you transfer learn or trained from scratch? and how many iterations did you go?

**Comment by Ghustwb** [comment]
person、car、bus、truck + background

**Comment by PiyalGeorge** [comment]
@Ghustwb  Great thanks alot
