### ISSUE TITLE
I can not run this code

### ISSUE THREAD

**Issue by coolzhangfeng** [Ghustwb/MobileNet-SSD-TensorRT#2]
it compiled suc,but it can not run,the error is 
mobileNetSSDTensorRT: NvPluginSSD.cu:795: virtual void nvinfer1::plugin::DetectionOutput::configure(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, int): Assertion `numPriors*numLocClasses*4 == inputDims[param.inputOrder[0]].d[0]' failed.
已放弃 (核心已转储)
can you tell me why?thanks very much

**Comment by Ghustwb** [comment]
If you use TensorRT4
You should modify some code in pluginImplement.cpp
uncomment line 525，comment line 524
uncomment line 533,534,535

**Comment by coolzhangfeng** [comment]
> If you use TensorRT4
> You should modify some code in pluginImplement.cpp
> uncomment line 525，comment line 524
> uncomment line 533,534,535

wawa,it has worked, I will read the code carefully.Do you have this development document for your project?It's hard to understand your idea by looking at code.
I have use tensorrt with pytorch and onnx,It's much simpler than your code.
We can talk more about tensor RT.
