### ISSUE TITLE
Showing caffeToTRTModel error when ./build/bin/mobileNet command

### ISSUE THREAD

**Issue by chinmayembedded** [Ghustwb/MobileNet-SSD-TensorRT#25]
nvidia@tegra-ubuntu:~/chinmay/MobileNet-SSD-TensorRT$ ./build/bin/mobileNet 
attempting to open cache file ../../model/MobileNetSSD_deploy.caffemodel.1.tensorcache
cache file not found, profiling network model
../../model/MobileNetSSD_deploy_iplugin.prototxt
../../model/MobileNetSSD_deploy.caffemodel
CaffeParser: Could not open file ../../model/MobileNetSSD_deploy.caffemodel
CaffeParser: Could not parse model file
mobileNet: /home/nvidia/chinmay/MobileNet-SSD-TensorRT/tensorNet.cpp:105: bool TensorNet::caffeToTRTModel(const char*, const char*, const std::vector<std::__cxx11::basic_string<char> >&, unsigned int, std::ostream&): Assertion `blobNameToTensor != nullptr' failed.
Aborted (core dumped)

I have downloaded the source code and trying to run it with the steps provided. When ./build/bin/mobileNet command used, it shows above error.

Package versions installed
tensorrt 4
cudnn 7
opencv 3

Can you help me with above issue?

**Comment by chinmayembedded** [comment]
@Ghustwb Please help

**Comment by AaaWsqL** [comment]
replace the weight file path in main.cpp with absolute path. It worked for me!

**Comment by chinmayembedded** [comment]
@AaaWsqL Thanks! it worked.
