### ISSUE TITLE
Memory leakage when kept running for some time

### ISSUE THREAD

**Issue by chinmayembedded** [Ghustwb/MobileNet-SSD-TensorRT#26]
I am trying to run the same code in the repository for the some time. However, the memory usage increases every second. 

_**RAM 7756/7851MB**_ (lfb 5x4MB) CPU [5%@2035,0%@2035,4%@2035,21%@2035,5%@2035,5%@2035] BCPU@50.5C MCPU@50.5C GPU@48C PLL@50.5C Tboard@45C Tdiode@47.75C PMIC@100C thermal@49.5C VDD_IN 4667/9426 VDD_CPU 626/4204 VDD_GPU 184/841 VDD_SOC 884/1035 VDD_WIFI 0/10 VDD_DDR 1284/1893
_**RAM 7757/7851MB**_ (lfb 5x4MB) CPU [5%@2035,0%@2035,0%@2035,11%@2035,14%@2035,6%@2035] BCPU@50.5C MCPU@50.5C GPU@48C PLL@50.5C Tboard@45C Tdiode@47.75C PMIC@100C thermal@49.5C VDD_IN 4431/9423 VDD_CPU 627/4202 VDD_GPU 147/840 VDD_SOC 885/1035 VDD_WIFI 0/10 VDD_DDR 1284/1892
_**RAM 7758/7851MB**_ (lfb 5x4MB) CPU [10%@2035,0%@2035,0%@2035,19%@2035,15%@2035,8%@2035] BCPU@50.5C MCPU@50.5C GPU@48C PLL@50.5C Tboard@45C Tdiode@47.75C PMIC@100C thermal@49.5C VDD_IN 4519/9420 VDD_CPU 737/4200 VDD_GPU 184/840 VDD_SOC 885/1035 VDD_WIFI 0/10 VDD_DDR 1303/1892
RAM 7759/7851MB (lfb 5x4MB) CPU [12%@2035,0%@2035,0%@2035,17%@2035,4%@2035,4%@2035] BCPU@50.5C MCPU@50.5C GPU@48C PLL@50.5C Tboard@45C Tdiode@47.75C PMIC@100C thermal@49.5C VDD_IN 4339/9416 VDD_CPU 627/4197 VDD_GPU 184/839 VDD_SOC 885/1035 VDD_WIFI 0/10 VDD_DDR 1284/1891
_**RAM 7759/7851MB**_ (lfb 5x4MB) CPU [13%@2035,0%@2035,0%@2035,12%@2035,8%@2035,7%@2035] BCPU@50.5C MCPU@50.5C GPU@48C PLL@50.5C Tboard@45C Tdiode@47.75C PMIC@100C thermal@49.2C VDD_IN 4394/9413 VDD_CPU 627/4195 VDD_GPU 147/839 VDD_SOC 885/1035 VDD_WIFI 0/10 VDD_DDR 1284/1891

And after some time the process is killed. Can you suggest a method to avoid the memory leakage?

**Comment by chinmayembedded** [comment]
@Ghustwb Can you look into the issue described?

**Comment by zacario-li** [comment]
@chinmayembedded modify main.cpp, line 176, add `cudaFree(imgCUDA);`

**Comment by chinmayembedded** [comment]
@zacario-li Ya i did put the cudafree lines in the loop. It solved the issue
