### ISSUE TITLE
请问怎么训练模型？

### ISSUE THREAD

**Issue by wangkailovebaojiakun** [Ghustwb/MobileNet-SSD-TensorRT#29]
想要训练自己的模型，请问有训练模型的代码么？

**Comment by Ghustwb** [comment]
训练的代码和tensorRT没有关系




在2019年03月18日 16:44，wangkailovebaojiakun<notifications@github.com> 写道：

想要训练自己的模型，请问有训练模型的代码么？

**Comment by wangkailovebaojiakun** [comment]
我用https://github.com/chuanqi305/MobileNet-SSD训练出的模型，但是失败了，”Weights for layer conv0 doesn't exist
CaffeParser: ERROR: Attempting to access NULL weights“，请问应该怎么训练呢
