### ISSUE TITLE
no result output

### ISSUE THREAD

**Issue by yiboliu31** [Ghustwb/MobileNet-SSD-TensorRT#3]
I found a strange error
I have changed my prototxt and code as you did, , and my classification is 9
but when I use my caffemodel ,there is no result of output, I don't know why

By the way , when I use your model and protoxt , I comment the "void cudaSoftmax".
But the result is correct
If I don't do that , there is an  error , "undefined reference to 'cudaSoftmax(int, int,float*,float*)' 

Could you please give me some suggestions?Thanks

**Comment by Ghustwb** [comment]
If you change the num of classfication,you should modify some code.such as softmax layer,detetction_out layer...

**Comment by PiyalGeorge** [comment]
@yiboliu31 @Ghustwb  I have a model(mobilenet-SSD, trained with custom data -class-7) that works. will it run on TensorRT, if i simply replace the caffemodel in this repo with my model? I've been sitting on this for  days. Please help.
