### ISSUE TITLE
train.prototxt of MobileNet-SSD-TensorRT for custom training

### ISSUE THREAD

**Issue by PiyalGeorge** [Ghustwb/MobileNet-SSD-TensorRT#4]
Hi @Ghustwb , I've been looking into this repo, its an awesome work, i've been looking for the exact same. But I'm trying to train a caffe model with my custom dataset. Please help me

**Comment by Ghustwb** [comment]
Hi
How can I help you




On 10/29/2018 15:28，PiyalGeorge<notifications@github.com> wrote：

Hi @Ghustwb , I've been looking into this repo, its an awesome work, i've been looking for the exact same. But I'm trying to train a caffe model with my custom dataset. Please help me

**Comment by PiyalGeorge** [comment]
@Ghustwb  Thanks for the response. i've trained my model with dataset using https://github.com/chuanqi305/MobileNet-SSD . I've seen the deploy.prototxt file in your repo. i dont know how to modify the train.prototxt , test.prototxt files. Can you please help me providing train.prototxt and test.prototxt to train on my custom dataset?

**Comment by Ghustwb** [comment]
OK
I think you should read the repo( https://github.com/chuanqi305/MobileNet-SSD )carefully,there is a script file,help you generate the train.prototxt,test.prototxt,deploy.prototxt 






On 10/29/2018 17:08，PiyalGeorge<notifications@github.com> wrote：

Thanks for the response. i've trained my model with dataset using https://github.com/chuanqi305/MobileNet-SSD . I've seen the deploy.prototxt file in your repo. i dont know how to modify the train.prototxt , test.prototxt files. Can you please help me providing train.prototxt and test.prototxt to train on my custom dataset?

**Comment by PiyalGeorge** [comment]
@Ghustwb , Yeah i got it, and using that i have trained a model with my custom dataset for myself. but in the deploy.prototxt file in your repo has fields like 'IPlugin', which is causing me this error- Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: IPlugin

**Comment by PiyalGeorge** [comment]
Hey, @Ghustwb When i use my caffemodel generated using custom dataset,  do i need to run cmake commands again inorder to get the output?

**Comment by yiboliu31** [comment]
@PiyalGeorge IPlugin means the layer that TensorRT doesn't  support ，if you don't use TensorRT ,change it to your original layer name

**Comment by PiyalGeorge** [comment]
Hi, @yiboliu31  , thanks for responding. I'm quite new to deep learning. I have trained a model using my custom dataset in mobileNet-SSD. Its working successfully. My problem is - I'm trying to implement the same in TensorRT in Jetson Tx2. But i don't know how to do that. Please kindly help me. How to make use of your repo. Please.
