### ISSUE TITLE
Assertion `(inputs[0].d[0])*(inputs[0].d[1]) % OutC == 0' failed

### ISSUE THREAD

**Issue by PiyalGeorge** [Ghustwb/MobileNet-SSD-TensorRT#6]
attempting to open cache file ../../model/MobileNetSSD_deploy.caffemodel.1.tensorcachecache file not found, profiling network model
../../model/MobileNetSSD_deploy_iplugin.prototxt
../../model/MobileNetSSD_deploy.caffemodel
mobileNet: /home/nvidia/MobileNet-SSD-TensorRT-master/pluginImplement.h:75: nvinfer1::Dims Reshape::getOutputDimensions(int, const nvinfer1::Dims*, int) [with int OutC = 5]: Assertion `(inputs[0].d[0])*(inputs[0].d[1]) % OutC == 0' failed.Aborted (core dumped)

Why am i getting this error?, Is there somewhere else than other than pluginImplement.h, and pluginImplement.cpp i need to make changes? Please kindly help

**Comment by Ghustwb** [comment]
I think you should to read the tensorRT developer guide.
When you load the caffemodel and prototxt, it could generate cache file. It can reduce the time you  load caffemodel and prototxt next time. 
If you modified the parameters of layer,  you should regenerate the cache file.
