### ISSUE TITLE
Weights for layer conv0 doesn't exist

### ISSUE THREAD

**Issue by ghost** [Ghustwb/MobileNet-SSD-TensorRT#8]
I run your code in tx1, when run mobilenet.bin and find this error, how to debug this error

**Comment by Ghustwb** [comment]
Regenerating the cache file

**Comment by ghost** [comment]
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 0 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Weights for layer conv0 doesn't exist
CaffeParser: ERROR: Attempting to access NULL weights
Weights for layer conv0 doesn't exist
CaffeParser: ERROR: Attempting to access NULL weights
Parameter check failed at: ../builder/Network.cpp::addConvolution::40, condition: kernelWeights.values != NULL
error parsing layer type Convolution index 0
mobileNet: /home/nvidia/Desktop/MobileNet-SSD-TensorRT-master/tensorNet.cpp:105: bool TensorNet::caffeToTRTModel(const char*, const char*, const std::vector<std::__cxx11::basic_string<char> >&, unsigned int, std::ostream&): Assertion `blobNameToTensor != nullptr' failed.

**Comment by ghost** [comment]
when I run your code and find this error, do you mean re run mobilenet.bin? I think maybe protobuf's problem but I find protobuf is newest version in tx1

**Comment by itkt** [comment]
I have this problem. How you solved it?
